# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-22 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=30, unique=True)),
                ('genre', models.CharField(max_length=15)),
                ('icon', models.ImageField(blank=True, upload_to='game_images')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('game',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchID', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('passRequired', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('full', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrim_finder_app.Games')),
            ],
            options={
                'ordering': ('matchID',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(default='', max_length=15)),
                ('passRequired', models.BooleanField(default=False)),
                ('full', models.BooleanField(default=False)),
                ('image', models.ImageField(default='team_images/default.jpg', upload_to='team_images')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('teams', models.ManyToManyField(to='scrim_finder_app.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(to='scrim_finder_app.userProfile'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='scrim_finder_app.Team'),
        ),
    ]
