# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='teamsPlayed',
            field=models.ManyToManyField(to='scrim_finder_app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamsPlaying',
            field=models.ManyToManyField(to='scrim_finder_app.Team'),
        ),
    ]
