# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='defaultUser.PNG', upload_to='profile_images'),
        ),
    ]
