# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrim_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('userName',)},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='userName',
        ),
    ]
