# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='teamsPlaying',
            new_name='teams',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='matches',
        ),
        migrations.AddField(
            model_name='match',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='passRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='password',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
