# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim_finder_app', '0002_auto_20170319_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='passRequired',
            field=models.BooleanField(default=False),
        ),
    ]
